/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#abadaf",
        "on-secondary-fixed-variant": "#533ea7",
        "inverse-on-surface": "#9a9d9f",
        "background": "#f5f7f9",
        "primary-container": "#9396ff",
        "on-tertiary-fixed-variant": "#6e1354",
        "surface-container-high": "#dfe3e6",
        "on-tertiary-fixed": "#3b002b",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d9dde0",
        "on-primary-fixed-variant": "#0e009d",
        "tertiary": "#963776",
        "error": "#b41340",
        "surface-dim": "#d0d5d8",
        "on-secondary-container": "#4a349d",
        "tertiary-fixed-dim": "#ef81c4",
        "surface-container": "#e5e9eb",
        "on-secondary": "#f6f0ff",
        "on-tertiary": "#ffeef4",
        "surface-container-low": "#eef1f3",
        "on-tertiary-container": "#63054a",
        "surface-tint": "#4647d3",
        "secondary-dim": "#523da6",
        "on-error": "#ffefef",
        "inverse-surface": "#0b0f10",
        "secondary-fixed": "#d6cbff",
        "error-container": "#f74b6d",
        "surface": "#f5f7f9",
        "primary-dim": "#3939c7",
        "surface-variant": "#d9dde0",
        "on-secondary-fixed": "#361c89",
        "on-background": "#2c2f31",
        "tertiary-container": "#ff8ed2",
        "on-error-container": "#510017",
        "on-surface": "#2c2f31",
        "on-primary-fixed": "#000000",
        "outline": "#747779",
        "secondary-fixed-dim": "#c8bbff",
        "error-dim": "#a70138",
        "primary": "#4647d3",
        "tertiary-dim": "#882a69",
        "on-primary": "#f4f1ff",
        "inverse-primary": "#8083ff",
        "secondary": "#5e4ab3",
        "primary-fixed": "#9396ff",
        "on-primary-container": "#0a0081",
        "surface-bright": "#f5f7f9",
        "on-surface-variant": "#595c5e",
        "primary-fixed-dim": "#8387ff",
        "tertiary-fixed": "#ff8ed2",
        "secondary-container": "#d6cbff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
}
